@memoryId = 60aac7ec556af4e3c526e641
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFhYjdhNmQxZGZjZmNhZWQ1YTM4MTkiLCJpYXQiOjE2MjE4NDQ0NzgsImV4cCI6MTYyMTg4NzY3OH0.3BaN4_c7rBiNaJL2YrMTAAezwcGZnJL_ipVwjWYceN4

### MEMORY ROUTES

### Get all memories
GET http://localhost:4000/api/memories

### Get single memory
GET http://localhost:4000/api/memories/60aa833f32789a73f7720e05


### Create memory
POST http://localhost:4000/api/memories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiODJhM2RlNmI5MmE0NTdlMjk3ZmYiLCJpYXQiOjE2MjE4NTI4NjEsImV4cCI6MTYyMTg5NjA2MX0.4Lr6Q67jjKxB-pwleH6k2GGW5F-4amUf-D4_xvqa3BQ
content-type: application/json

{
  "title": "test memory 211",
  "location": "London2",
  "date": "2020-05-022",
  "imageUrl": "https://blog.dys.com/wp-content/uploads/2021/03/One-version-of-the-truth-in-SOP-Our-collective-memory.jpg",
  "description": "2so that's my test memory 11",
  "tags": ["stuff", "more stuff"]
}

### Edit memory
PUT http://localhost:4000/api/memories/60ab8482526419a4b01bc478
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiODJhM2RlNmI5MmE0NTdlMjk3ZmYiLCJpYXQiOjE2MjE4NTI4NjEsImV4cCI6MTYyMTg5NjA2MX0.4Lr6Q67jjKxB-pwleH6k2GGW5F-4amUf-D4_xvqa3BQ
content-type: application/json

{
  "title": "that day y'know?",
  "location": "new cit",
  "date": "1990-01-01",
  "imageUrl": "fake UR",
  "description": "fake memory 23",
  "tags": ["fake", "more fake"]
}


### Delete memory
DELETE http://localhost:4000/api/memories/60ab82fbde6b92a457e29800
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiODJhM2RlNmI5MmE0NTdlMjk3ZmYiLCJpYXQiOjE2MjE4NTI4NjEsImV4cCI6MTYyMTg5NjA2MX0.4Lr6Q67jjKxB-pwleH6k2GGW5F-4amUf-D4_xvqa3BQ
content-type: application/json


### COMMENT ROUTES

## POST A COMMENT ON A MEMORY
POST http://localhost:4000/api/memories/60aa833f32789a73f7720e05/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiODJhM2RlNmI5MmE0NTdlMjk3ZmYiLCJpYXQiOjE2MjE4NTI4NjEsImV4cCI6MTYyMTg5NjA2MX0.4Lr6Q67jjKxB-pwleH6k2GGW5F-4amUf-D4_xvqa3BQ
content-type: application/json

{
  "text": "TEST"

}

### EDIT A COMMENT

PUT http://localhost:4000/api/memories/60ab8482526419a4b01bc478/comment/60ab8a2eccf064a619c7d264
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiODJhM2RlNmI5MmE0NTdlMjk3ZmYiLCJpYXQiOjE2MjE4NTI4NjEsImV4cCI6MTYyMTg5NjA2MX0.4Lr6Q67jjKxB-pwleH6k2GGW5F-4amUf-D4_xvqa3BQ
content-type: application/json

{
  "text": "TEST EDIT"

}


### DELETE A COMMENT

DELETE http://localhost:4000/api/memories/60ab8482526419a4b01bc478/comment/60ab8b24426f2da659fc58a2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiODJhM2RlNmI5MmE0NTdlMjk3ZmYiLCJpYXQiOjE2MjE4NTI4NjEsImV4cCI6MTYyMTg5NjA2MX0.4Lr6Q67jjKxB-pwleH6k2GGW5F-4amUf-D4_xvqa3BQ
content-type: application/json



### USER ROUTES

### CREATE A NEW USER
POST http://localhost:4000/api/register
Content-Type: application/json

{
  "username": "user4",
  "email": "user2mail34",
  "emailConfirmation": "user2mail34",
  "password": "2",
  "passwordConfirmation":"2"
}


### LOG IN EXISTING USER
POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "user2mail34",
  "password": "2"
}




