
### MEMORY ROUTES

GET http://localhost:4000/api/memories


### USER ROUTES



### CREATE A NEW USER
POST http://localhost:4000/api/register
Content-Type: application/json

{
  "username": "user233",
  "email": "user2mail3",
  "emailConfirmation": "user2mail3",
  "password": "2",
  "passwordConfirmation":"2"
}


### LOG IN EXISTING USER
POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "user2mail3",
  "password": "2"
}


